CREATE DATABASE music_works;

USE music_works;

CREATE TABLE artists (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL
  link VARCHAR(255) NOT NULL
  vote VARCHAR(255) NOT NULL
  
);

